--- 
- name: edgestream-hub
  hosts: localhost
  connection: local
  
  vars:
    version: "2.0"
    mode: "install"

  roles:
    - {role: "core-installer", tags: ["core-installer"]}
    - {role: "post-init", tags: ["post-init"]}
    - {role: "netflow-installer", tags: ["netflow-installer"]}
    - {role: "core-settings", tags: ["core-settings"]}
    - {role: "certificate-settings", tags: ["certificate-settings"]}
    - {role: "vector-settings", tags: ["vector-settings"]}
    - {role: "netflow-settings", tags: ["netflow-settings"]}
    - {role: "wec-settings", tags: ["wec-settings"]}
    - {role: "o365audit-installer", tags: ["o365audit-installer"]}
    - {role: "o365audit-settings", tags: ["o365audit-settings"]}
    - {role: "syslog-settings", tags: ["syslog-settings"]}
    - {role: "network-settings", tags: ["network-settings"]}
    - {role: "dns-settings", tags: ["dns-settings"]}
    - {role: "ntp-settings", tags: ["ntp-settings"]}
    - {role: "vpn-settings", tags: ["vpn-settings"]}

